# Generated by Django 3.2.1 on 2022-09-11 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen_reporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen_reporter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
