# Generated by Django 3.2.1 on 2022-10-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20220929_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
