# Generated by Django 3.2.1 on 2022-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_category_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='County_name',
        ),
        migrations.AddField(
            model_name='location',
            name='Postal_Adress',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='postal_Code',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
