# Generated by Django 3.2.1 on 2022-10-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20221006_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='citizen_reporter',
        ),
        migrations.RemoveField(
            model_name='location',
            name='citizen_reporter',
        ),
        migrations.DeleteModel(
            name='Citizen_reporter',
        ),
    ]
