# Generated by Django 3.2.1 on 2022-10-23 13:06

from django.db import migrations, models
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20221006_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 14, 2, 27, 794036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
