# Generated by Django 3.2.1 on 2022-10-23 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20221023_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 9, 28, 405791, tzinfo=utc)),
        ),
    ]
