# Generated by Django 3.2.1 on 2022-10-23 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_alter_evidence_happened_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='evidence',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 12, 15, 699651, tzinfo=utc)),
        ),
    ]
