# Generated by Django 3.2.1 on 2022-10-23 13:14

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20221023_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 14, 7, 323014, tzinfo=utc)),
        ),
    ]
