# Generated by Django 3.2.1 on 2022-10-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20221023_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
