# Generated by Django 3.2.1 on 2022-10-23 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_delete_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.FileField(upload_to='media/')),
                ('happened_on', models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 35, 48, 586024, tzinfo=utc))),
                ('description', models.TextField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
