# Generated by Django 3.2.1 on 2022-10-23 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='happened_on',
        ),
        migrations.AddField(
            model_name='evidence',
            name='happened_oon',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 42, 20, 879529, tzinfo=utc)),
        ),
    ]
