# Generated by Django 3.2.1 on 2022-10-23 14:13

from django.db import migrations, models
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_alter_evidence_happened_oon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='happened_oon',
        ),
        migrations.AddField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 14, 2, 27, 794036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.TextField(max_length=60),
        ),
    ]
