# Generated by Django 3.2.1 on 2022-10-23 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0022_remove_evidence_happened_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 17, 49, 24, 854683)),
        ),
    ]
