# Generated by Django 3.2.1 on 2022-10-23 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0024_auto_20221023_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='reporter',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 18, 44, 34, 527656)),
        ),
    ]
