# Generated by Django 4.1.2 on 2023-02-15 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0025_auto_20221023_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='happened_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 58, 56, 867734)),
        ),
    ]
